#!/bin/bash

echo "All repos"
scc --exclude-file "*_test.go" --exclude-dir "vendor" --exclude-dir "node_modules" --exclude-dir "build" --exclude-dir "dist" --exclude-dir ".git" --exclude-dir ".idea" --exclude-dir ".vscode" --exclude-dir ".cache" --exclude-dir ".mypy_cache" --exclude-dir "__pycache__" --exclude-dir ".pytest_cache" --exclude-dir ".tox" --exclude-dir ".eggs" --exclude-dir ".venv" --exclude-dir "venv" --exclude-dir "env" --exclude-dir "envs" --exclude-dir "bin" --exclude-dir "obj" --exclude-dir "out" --exclude-dir "target"
echo "tui-base"
scc tui-base --exclude-file "*_test.go" --exclude-dir "vendor" --exclude-dir "node_modules" --exclude-dir "build" --exclude-dir "dist" --exclude-dir ".git" --exclude-dir ".idea" --exclude-dir ".vscode" --exclude-dir ".cache" --exclude-dir ".mypy_cache" --exclude-dir "__pycache__" --exclude-dir ".pytest_cache" --exclude-dir ".tox" --exclude-dir ".eggs" --exclude-dir ".venv" --exclude-dir "venv" --exclude-dir "env" --exclude-dir "envs" --exclude-dir "bin" --exclude-dir "obj" --exclude-dir "out" --exclude-dir "target"
echo "dash"
scc dash --exclude-file "*_test.go" --exclude-dir "vendor" --exclude-dir "node_modules" --exclude-dir "build" --exclude-dir "dist" --exclude-dir ".git" --exclude-dir ".idea" --exclude-dir ".vscode" --exclude-dir ".cache" --exclude-dir ".mypy_cache" --exclude-dir "__pycache__" --exclude-dir ".pytest_cache" --exclude-dir ".tox" --exclude-dir ".eggs" --exclude-dir ".venv" --exclude-dir "venv" --exclude-dir "env" --exclude-dir "envs" --exclude-dir "bin" --exclude-dir "obj" --exclude-dir "out" --exclude-dir "target"
echo "snap"
scc snap --exclude-file "*_test.go" --exclude-dir "vendor" --exclude-dir "node_modules" --exclude-dir "build" --exclude-dir "dist" --exclude-dir ".git" --exclude-dir ".idea" --exclude-dir ".vscode" --exclude-dir ".cache" --exclude-dir ".mypy_cache" --exclude-dir "__pycache__" --exclude-dir ".pytest_cache" --exclude-dir ".tox" --exclude-dir ".eggs" --exclude-dir ".venv" --exclude-dir "venv" --exclude-dir "env" --exclude-dir "envs" --exclude-dir "bin" --exclude-dir "obj" --exclude-dir "out" --exclude-dir "target"
echo "inspector"
scc inspector --exclude-file "*_test.go" --exclude-dir "vendor" --exclude-dir "node_modules" --exclude-dir "build" --exclude-dir "dist" --exclude-dir ".git" --exclude-dir ".idea" --exclude-dir ".vscode" --exclude-dir ".cache" --exclude-dir ".mypy_cache" --exclude-dir "__pycache__" --exclude-dir ".pytest_cache" --exclude-dir ".tox" --exclude-dir ".eggs" --exclude-dir ".venv" --exclude-dir "venv" --exclude-dir "env" --exclude-dir "envs" --exclude-dir "bin" --exclude-dir "obj" --exclude-dir "out" --exclude-dir "target"